specialties:
  - Cardiology
  - Dermatology
  - Disaster medicine
  - Endocrinology
  - General Practice
  - Obstetrics
schools:
  - Bayero University
  - Ahmadu Bello University
  - Ogun State University
  - University of Ilorin
degrees:
  - L.S.M.
  - M.B.
  - F.M.C.P.
  - B.S.
